### ISSUE TITLE
现在的weex-toolkit工具，是不是还在测试过程中？

### ISSUE THREAD

**Issue by AugTang** [apache/incubator-weex-cli#242]
在安装weex-toolkit过程中，会出现不一样的问题。（windows环境）

1.安装成功，但是debug功能无法使用。
2.安装成功，运行weex命令，也会报错。

。。。。。。。。。。。。。。

问题很多，建议先把环境问题解决好，再发布，这样我们这些码农也不至于将项目一拖再拖

@erha19

**Comment by erha19** [comment]
@AugTang The current test coverage is lower, and most of the basic functional testing, follow-up I will increase by adding ways to improve the test. 
At present, most of the problems on windows are mainly caused by inconsistencies in the developer environment. For example, the environment required for ·node-gpy· compilation is lacking in development #236 , and chromium cannot be downloaded for network problems #224. These environmental problems need to be deployed by developers, at least my own windows computer tool is up and running, I will fill in the follow-up update this one hint.
Incidentally, all of the current `weex` tools are basically on me, due to limited energy I will not carry out too much platform testing, which is certainly there will be some problems that may exist, if you have encountered any problems during use welcome to create `issues` or `pull request` to help the tool to do better Instead of complaining.

**Comment by AugTang** [comment]
感谢您的付出，也很感谢您能每天在百忙之中，回答我们的问题，希望能够把最新的命令和操作方式在文档上面及时更新，感谢！ @erha19
