### ISSUE TITLE
Can't create any project with weex

### ISSUE THREAD

**Issue by Alive2212** [apache/incubator-weex-cli#252]
my os is ubuntu 16.04 and in 64bit
i want to create new project with this steps

`$ npm install -g weex-toolkit
`

and 

`$ weex create awesome-project
`

and after i use this command weex crached and log is :

`Error: Cannot find module 'weex-previewer'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.resolve (internal/module.js:18:19)
    at Object.<anonymous> (/usr/lib/node_modules/weex-toolkit/bin/weex.js:90:66)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
`

and when i used following command i have a another error

`weex update weex-previewer@latest
`
errors: 

update package "weex-previewer" now? Yes
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-01-23T20_17_08_502Z-debug.log

**Comment by erha19** [comment]
@Alive2212 There should have some error log while you install the `weex-toolkit`, try to install it use `--no-optional` tag, and we suppose you to use mac os.

**Comment by Alive2212** [comment]
thanks for your hint but after i used that command, i have another error:


module.js:487
    throw err;
    ^

`Error: Cannot find module './gituser'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/alive/.xtoolkit/node_modules/weexpack/lib/utils/index.js:15:15)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
`

**Comment by jorjodell** [comment]
Same problem. Deepin 15.5

**Comment by erha19** [comment]
@Alive2212 @adikjoro I have fixed it on [weex-pack/commit/3aebde4](https://github.com/weexteam/weex-pack/commit/3aebde40738b1a4aeb88805570a80439615d9bd6), you can run `weex update weexpack@latest` to fix this issue.

**Comment by fantasysea** [comment]
centos系统:
Linux cheetah 4.14.14-x86_64-linode94 #4 SMP Tue Jan 23 01:06:56 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

sudo npm install weex-toolkit -g
安装失败,
报错:
'''
root@cheetah weex]# sudo npm install weex-toolkit -g
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha1-Hcb4dQ6Jtrl53l/kSqmTsaIZImE= integrity checksum failed when using sha1: wanted sha1-Hcb4dQ6Jtrl53l/kSqmTsaIZImE= but got sha512-OTUb6iSKVR/98dGThRJ1BiyfwbuX10BVnkz89IpaerjTPRhDfMBfLsqmzxz5MiywUOW4M0Clta0o7rSxkfcuzw==. (31638 bytes)
npm WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
/root/node-v8.9.4-linux-x64/bin/weex -> /root/node-v8.9.4-linux-x64/lib/node_modules/weex-toolkit/bin/weex.js

> weex-previewer@1.4.6 postinstall /root/node-v8.9.4-linux-x64/lib/node_modules/weex-toolkit/node_modules/weex-previewer
> node ./lib/hook/post-install.js

Error:permission denied.Please apply the write premission to the directory: "/root" 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/weex-toolkit/node_modules/xtoolkit/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@https://registry.npmjs.org/fsevents/-/fsevents-1.1.3.tgz: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/weex-toolkit/node_modules/weex-previewer/node_modules/weex-builder/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/weex-toolkit/node_modules/weex-previewer/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/weex-toolkit/node_modules/weex-builder/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/weex-toolkit/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ weex-toolkit@1.2.9
added 401 packages, removed 334 packages, updated 127 packages and moved 3 packages in 26.732s
[root@cheetah weex]# mkdir ~/.xtoolkit && chmod 777 ~/.xtoolkit
[root@cheetah weex]# sudo npm install weex-toolkit -g
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/weex-toolkit/node_modules/xtoolkit/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@https://registry.npmjs.org/fsevents/-/fsevents-1.1.3.tgz: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-02-08T07_41_17_752Z-debug.log
'''

**Comment by evandrojr** [comment]
I fixed it with:
npm i -g npm
